services:
  app:
    build: .
    container_name: app-dev
    ports:
      - "3000:3000"
    networks:
      - automated-reasoning-network
    mem_limit: 512m
    cpus: 1.0
    depends_on:
      - rabbitmq
      - redis
    environment:
      - .env
  rabbitmq:
    image: rabbitmq:4.2.2-management
    container_name: rabbitmq-dev
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: dev
      RABBITMQ_DEFAULT_PASS: dev
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

  redis:
    image: redis:8.4.0
    container_name: redis-dev
    ports:
      - "6379:6379"
    networks:
      - automated-reasoning-network
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes

volumes:
  rabbitmq_data:
  redis_data:

networks:
  automated-reasoning-network:
    driver: bridge
